install.packages("shiny", dependencies=TRUE)
install.packages("readxl", dependencies=TRUE)
install.packages("lubridate", dependencies=TRUE)
install.packages("plyr", dependencies=TRUE)
install.packages("DT", dependencies=TRUE)
install.packages("reshape", dependencies=TRUE)
install.packages("caret", dependencies=TRUE)
# install.packages("htmlwidgets")
# install.packages("tidyr")
# install.packages("hexbin")
# install.packages("dplyr")
# install.packages("crosstalk")
# install.packages("purrr")
# install.packages("data.table")
# install.packages("plotly")
# #`htmlwidgets', `tidyr', `hexbin', `dplyr', `crosstalk', `purrr', `data.table